# Generated by Django 5.1 on 2024-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_id', models.IntegerField()),
                ('borrower_name', models.CharField(max_length=255)),
                ('total_loan_amount', models.FloatField()),
                ('outstanding_amount', models.FloatField()),
                ('due_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
